name: kube-downscaler
apiVersion: v1
version: 0.1.0
appVersion: 0.5.1
description:  A Helm chart for kube-downscaler
keywords:
- k8s pods scheduler
- scheduled lifecycle
sources:
- https://github.com/hjacobs/kube-downscaler
